# Site settings
title: UW Labs
description: > # this means to ignore newlines until "baseurl:"
  Utility Warehouse Ltd Labs Blogposts

# Build settings
markdown: kramdown

github_labs_username: uw-labs
github_username: utilitywarehouse